name: "Bump version"
branding:
  icon: "package"
  color: "red"
description: "Bump version and push."
author: "VladDaniliuk"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of APK to release."
runs:
  using: "docker"
  image: "Dockerfile"
